version: '3'
services:
  postgres:
    restart: always
    image: 'postgres:latest'
  redis:
    restart: always
    image: 'redis:latest'
  api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./server/
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis 
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password 
      - PGPORT=5432
  worker:
    build:
      dockerfile: Dockerfile
      context: ./worker
    volumes:
        - /app/node_modules
        - ./worker:/app
    restart: always
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
        - /app/node_modules
        - ./client:/app
    restart: always
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3050:80'
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    restart: always